version: '3'
# TO USE THIS COMBINATION, ADD THIS TO BAZELRC
#  build --remote_cache=172.25.0.101:8085
services:
  hazelcast_cache:
    image: hazelcast/hazelcast:latest
    restart: always
    networks:
      bazelcast:
        ipv4_address: 172.25.0.102

  remote_worker:
    image: murtis/bazel_remote_worker:latest
    restart: always
    ports:
      - "8085:8085"
    networks:
      bazelcast:
        ipv4_address: 172.25.0.101
    environment:
      LISTEN_PORT: 8085
      HAZELCAST_SEVER: 172.25.0.102
    depends_on:
      - hazelcast_cache

networks:
  bazelcast:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
